### ISSUE TITLE
Bug: search bar inputs handling failure

### ISSUE THREAD

**Issue by JasonBarahan** [JasonBarahan/TrackMyTransit#26]
Quoted from @carmen-chau in PR #23 :

The search bar does not properly handle inputs that were previously typed incorrectly, but then later on, are corrected prior to the "Submit button" being pressed.

   Eg:  In other words, if one were to type in "Arora Go" -> press Submit, an error dialog window would show up [Intended behaviour. However, if you were to insert a "u" between "A" and "r" such that the input is now "Aurora GO", this would still display an error dialog window. [Intended behavior is supposed to redirect user to the next view]

**Comment by JasonBarahan** [comment]
![Screenshot 2023-11-07 211820](https://github.com/JasonBarahan/TrackMyTransit/assets/122300705/7bacbd3c-d181-4963-872d-3dfd4c3a4d02)

**Comment by jacqnnn** [comment]
error caused by e.getKeyChar()

**Comment by JasonBarahan** [comment]
This branch was merged witb a bug but was subsequently fixed in PR #35
