### ISSUE TITLE
Use Case #3: Implement test

### ISSUE THREAD

**Issue by jacqnnn** [JasonBarahan/TrackMyTransit#43]
### Need to implement test for use case #44 :

> As a transit commuter, I would want to retrieve a list (at most 3)of departing train/buses. 

### Unit test to be implemented:

- [X] Check when there are >3 vehicles retrieved from api call, the 3 vehicles displayed depart the earliest.
- [X] Check when error occurs during api call.
- [X] Check when there are <=3 vehicles retrieved from api call, all vehicles are displayed.
- [x] Check if vehicle info is displayed.
- [x] Check "Show Map" button exists.

**Comment by carmen-chau** [comment]
@jacqnnn , Please remember that you DO NOT need to do end to end testing! Just unit test for your interactor should be sufficient
